import fs from "node:fs";

import { GENRES, STYLES, TAGS } from "../config/constants.js";
import { settings } from "../config/settings.js";
import { normalizePreset } from "./presetsService.js";

const TWEAK_KEYS = ["low_end", "punch", "presence", "brightness", "warmth", "width", "loudness"];

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

function slugify(name) {
  return String(name || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

function normalizeTweaks(raw = {}) {
  const out = {};
  for (const key of TWEAK_KEYS) {
    const val = Number(raw?.[key] ?? 0);
    out[key] = Number.isFinite(val) ? clamp(val, -1, 1) : 0;
  }
  return out;
}

// Accepts either shape:
//  - a full professional preset (same as one entry of mixing_presets.json,
//    with "processing"/"quality_control"/"output" blocks — e.g. generated by
//    an LLM), which is stored and applied whole via preset_dsp_engine, or
//  - the lightweight {genre, style, tags, tweaks} shape for the existing
//    genre-based engine.
// Either way "name" is required since a standalone file has no parent key.
function parseImportedPreset(raw) {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    throw new Error("Preset file must be a JSON object");
  }

  const slug = slugify(raw.name);
  if (!slug) {
    throw new Error("Preset needs a non-empty 'name' field");
  }
  if (!GENRES.includes(raw.genre)) {
    throw new Error(`genre must be one of: ${GENRES.join(", ")}`);
  }
  const style = raw.style || "modern";
  if (!STYLES.includes(style)) {
    throw new Error(`style must be one of: ${STYLES.join(", ")}`);
  }
  const tags = Array.isArray(raw.tags) ? raw.tags : [];
  const unknownTags = tags.filter((tag) => !TAGS.includes(tag));
  if (unknownTags.length) {
    throw new Error(`Unknown tag(s): ${unknownTags.join(", ")}`);
  }
  if (raw.processing && (typeof raw.processing !== "object" || Array.isArray(raw.processing))) {
    throw new Error("'processing' must be a JSON object");
  }
  const outputFormat = raw.output_format === "mp3" ? "mp3" : "wav";

  return {
    slug,
    preset: {
      display_name: raw.display_name || raw.name,
      description: raw.description || "",
      genre: raw.genre,
      style,
      tags,
      tweaks: normalizeTweaks(raw.tweaks),
      use_stem_separation: Boolean(raw.use_stem_separation),
      output_format: outputFormat,
      // Preserved verbatim — this is what makes an imported "full" preset a
      // real professional mix instead of an approximation via genre/tweaks.
      processing: raw.processing || null,
      quality_control: raw.quality_control || null,
      output: raw.output || null,
    },
  };
}

function readCustomPresetsFile() {
  try {
    return JSON.parse(fs.readFileSync(settings.customPresetsFile, "utf-8"));
  } catch {
    return {};
  }
}

export function listCustomPresets() {
  const stored = readCustomPresetsFile();
  return Object.entries(stored).map(([name, value]) => normalizePreset(name, value, { custom: true }));
}

export function importCustomPreset(jsonText) {
  let raw;
  try {
    raw = JSON.parse(jsonText);
  } catch {
    throw new Error("Preset file is not valid JSON");
  }

  const { slug, preset } = parseImportedPreset(raw);
  const stored = readCustomPresetsFile();
  stored[slug] = preset;
  fs.writeFileSync(settings.customPresetsFile, JSON.stringify(stored, null, 2));

  return normalizePreset(slug, preset, { custom: true });
}

export function deleteCustomPreset(name) {
  const stored = readCustomPresetsFile();
  if (!(name in stored)) {
    return false;
  }
  delete stored[name];
  fs.writeFileSync(settings.customPresetsFile, JSON.stringify(stored, null, 2));
  return true;
}
