import { GENRES, STYLES, TAGS, CATEGORIES, FLAVOURS_BY_CATEGORY } from "../config/constants.js";
import { getFirestore } from "../config/firebase.js";
import { normalizePreset } from "./presetsService.js";
import { listBuiltInPresets } from "./builtinPresetsService.js";

// Saved Artists live in Firestore, one doc per artist, scoped under the
// owning user — private per-account and durable across restarts/redeploys,
// unlike the local-disk JSON file this used to be:
//
//   users/{uid}/artists/{slug}
//     artist_name: "The Weeknd"
//     created_at: <Firestore Timestamp>
//     genre: "pop"
//     style: "modern"
//     tags: ["better_vocals", "louder"]
//     tweaks: { low_end, punch, presence, brightness, warmth, width, loudness }
//     use_stem_separation: false
//     output_format: "wav"
//     processing: {...} | null
//     quality_control: {...} | null
//     output: {...} | null
//
// Every doc has the exact same fields every time (nulls, not omissions) —
// same discipline the old local-file schema introduced, just backed by a
// real per-user database now instead of a single shared file on one disk.

const TWEAK_KEYS = ["low_end", "punch", "presence", "brightness", "warmth", "width", "loudness"];

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

function slugify(name) {
  return String(name || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

function normalizeTweaks(raw = {}) {
  const out = {};
  for (const key of TWEAK_KEYS) {
    const val = Number(raw?.[key] ?? 0);
    out[key] = Number.isFinite(val) ? clamp(val, -1, 1) : 0;
  }
  return out;
}

function artistsCollection(uid) {
  if (!uid) {
    throw new Error("Saved Artists require a signed-in user");
  }
  return getFirestore().collection("users").doc(uid).collection("artists");
}

// Accepts either shape:
//  - a full professional preset (same as one entry of mixing_presets.json,
//    with "processing"/"quality_control"/"output" blocks — e.g. generated by
//    an LLM), which is stored and applied whole via preset_dsp_engine, or
//  - the lightweight {genre, style, tags, tweaks} shape for the existing
//    genre-based engine.
// Either way a name is required (from the file or the override) since a
// standalone file has no parent key. artistName, when given, always wins —
// it's what the user typed in the "Saved Artists" UI, which matters more
// than whatever generic/technical name (if any) is baked into a JSON a
// preset might have been generated with (e.g. by an LLM).
function parseImportedPreset(raw, artistName) {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    throw new Error("Preset file must be a JSON object");
  }

  const resolvedName = artistName || raw.name || raw.display_name;
  const slug = slugify(resolvedName);
  if (!slug) {
    throw new Error("Preset needs a name — either an artist name or a non-empty 'name'/'display_name' field in the file");
  }
  if (raw.processing !== undefined && raw.processing !== null && (typeof raw.processing !== "object" || Array.isArray(raw.processing))) {
    throw new Error("'processing' must be a JSON object");
  }
  const hasProcessing = Boolean(raw.processing);

  // A full professional preset (has a "processing" block, e.g. exported
  // from Pro Mastering or generated externally) is a self-sufficient
  // instruction set for preset_dsp_engine — genre/style/tags are cosmetic
  // labels on it, not inputs the engine reads, so they're accepted as-is
  // rather than validated against the app's fixed enums. Only the legacy
  // tweak-based shape (no "processing") actually needs a real genre/style/
  // tag the adaptive engine understands, since those values drive it directly.
  let genre = raw.genre || "";
  let style = raw.style || "modern";
  let tags = Array.isArray(raw.tags) ? raw.tags : [];
  if (!hasProcessing) {
    if (!GENRES.includes(raw.genre)) {
      throw new Error(`genre must be one of: ${GENRES.join(", ")}`);
    }
    if (!STYLES.includes(style)) {
      throw new Error(`style must be one of: ${STYLES.join(", ")}`);
    }
    const unknownTags = tags.filter((tag) => !TAGS.includes(tag));
    if (unknownTags.length) {
      throw new Error(`Unknown tag(s): ${unknownTags.join(", ")}`);
    }
  } else {
    tags = tags.filter((tag) => TAGS.includes(tag));
  }
  const outputFormat = raw.output_format === "mp3" ? "mp3" : "wav";

  return {
    slug,
    artist: {
      artist_name: artistName || raw.display_name || raw.name,
      genre,
      style,
      tags,
      tweaks: normalizeTweaks(raw.tweaks),
      use_stem_separation: Boolean(raw.use_stem_separation),
      output_format: outputFormat,
      // Preserved verbatim — this is what makes an imported "full" preset a
      // real professional mix instead of an approximation via genre/tags.
      processing: raw.processing || null,
      quality_control: raw.quality_control || null,
      output: raw.output || null,
    },
  };
}

// Maps a stored artist doc to the flat {name, display_name, genre, ...}
// shape every preset (built-in or custom) is served as over the API.
function toPresetShape(slug, artist) {
  return normalizePreset(slug, { ...artist, display_name: artist.artist_name }, { custom: true });
}

// Per-user memo of the Saved Artists list: it was re-read in full (one
// billed read per preset) on every console load. Every write path in this
// module invalidates the user's entry; the TTL bounds staleness from edits
// made outside this process.
const LIST_TTL_MS = 10 * 60 * 1000;
const listMemo = new Map(); // uid -> { list, at }
export function invalidateCustomPresets(uid) {
  listMemo.delete(uid);
}

export async function listCustomPresets(uid) {
  const memo = uid ? listMemo.get(uid) : null;
  if (memo && Date.now() - memo.at < LIST_TTL_MS) return memo.list;
  const list = await listCustomPresetsUncached(uid);
  if (uid) {
    if (listMemo.size > 20_000) listMemo.clear();
    listMemo.set(uid, { list, at: Date.now() });
  }
  return list;
}

async function listCustomPresetsUncached(uid) {
  if (!uid) return [];
  const snapshot = await artistsCollection(uid).get();
  return snapshot.docs.map((doc) => toPresetShape(doc.id, doc.data()));
}

export async function getCustomPreset(name, uid) {
  const memo = uid ? listMemo.get(uid) : null;
  if (memo && Date.now() - memo.at < LIST_TTL_MS) {
    const hit = memo.list.find((p) => p.name === name);
    if (hit) return hit;
  }
  if (!uid) return null;
  const doc = await artistsCollection(uid).doc(name).get();
  return doc.exists ? toPresetShape(doc.id, doc.data()) : null;
}

export async function importCustomPreset(jsonText, artistName, uid) {
  let raw;
  try {
    raw = JSON.parse(jsonText);
  } catch {
    throw new Error("Preset file is not valid JSON");
  }

  const { slug, artist } = parseImportedPreset(raw, artistName);
  const record = { ...artist, created_at: new Date() };
  await artistsCollection(uid).doc(slug).set(record);
  invalidateCustomPresets(uid);

  return toPresetShape(slug, record);
}

export async function deleteCustomPreset(name, uid) {
  const ref = artistsCollection(uid).doc(name);
  const doc = await ref.get();
  if (!doc.exists) {
    return false;
  }
  await ref.delete();
  invalidateCustomPresets(uid);
  return true;
}

// ---- User-built presets (Direction controls) ---------------------------
// Created and edited from the console / My Presets, not imported as JSON.
// Stored in the same per-user collection as imported artist chains so
// /master resolves both the same way; kind "settings" marks them as
// editable adaptive-engine settings (genre/style/tags/tweaks/objective),
// as opposed to an imported literal "processing" chain.
const DIRECTIONS = new Set(["balanced", "warm", "punchy", "open", "clear", "custom"]);
const INTENSITIES = new Set(["subtle", "balanced", "strong"]);
const LOUDNESS = new Set(["natural", "streaming", "loud"]);
const MAX_USER_PRESETS = 100;

function validateSettings(body) {
  const name = String(body?.name || "").trim().slice(0, 60);
  if (!name) throw new Error("Give the profile a name.");
  if (!GENRES.includes(body.genre)) throw new Error(`genre must be one of: ${GENRES.join(", ")}`);
  const style = body.style || "modern";
  if (!STYLES.includes(style)) throw new Error(`style must be one of: ${STYLES.join(", ")}`);
  const tags = (Array.isArray(body.tags) ? body.tags : []).filter((t) => TAGS.includes(t));
  const category = body.category && CATEGORIES.includes(body.category) ? body.category : null;
  const flavour = category && body.flavour && (FLAVOURS_BY_CATEGORY[category] || []).includes(body.flavour) ? body.flavour : null;
  const d = body.direction || {};
  const direction = {
    tone: DIRECTIONS.has(d.tone) ? d.tone : "custom",
    intensity: INTENSITIES.has(d.intensity) ? d.intensity : "balanced",
    loudness: LOUDNESS.has(d.loudness) ? d.loudness : "streaming",
  };
  return {
    artist_name: name,
    description: String(body.description || "").trim().slice(0, 200),
    genre: body.genre,
    style,
    tags,
    tweaks: normalizeTweaks(body.tweaks),
    category,
    flavour,
    direction,
    use_stem_separation: false,
    output_format: body.output_format === "mp3" ? "mp3" : "wav",
    processing: null,
    kind: "settings",
  };
}

export async function createUserPreset(body, uid) {
  const record = validateSettings(body);
  let slug = slugify(record.artist_name);
  if (!slug) throw new Error("Give the preset a name with at least one letter or number.");
  const col = artistsCollection(uid);
  // Never overwrite an existing preset by creating one with the same name.
  // A built-in with the same slug would shadow it at /master (built-ins
  // resolve first), so that counts as taken too.
  const existing = await col.doc(slug).get();
  const shadowsBuiltIn = (await listBuiltInPresets()).some((p) => p.name === slug);
  if (existing.exists || shadowsBuiltIn) slug = `${slug}_${Date.now().toString(36).slice(-4)}`;
  const count = (await listCustomPresets(uid)).length;
  if (count >= MAX_USER_PRESETS) throw new Error(`You can keep up to ${MAX_USER_PRESETS} artist profiles — delete one first.`);
  const now = new Date().toISOString();
  await col.doc(slug).set({ ...record, created_at: now, updated_at: now });
  invalidateCustomPresets(uid);
  return toPresetShape(slug, { ...record, updated_at: now });
}

export async function updateUserPreset(slug, body, uid) {
  const ref = artistsCollection(uid).doc(slug);
  const doc = await ref.get();
  if (!doc.exists) {
    const error = new Error("Preset not found");
    error.status = 404;
    throw error;
  }
  if (doc.data()?.processing) {
    const error = new Error("This preset is an imported processing chain — edit its JSON and re-import it instead.");
    error.status = 409;
    throw error;
  }
  const record = validateSettings(body);
  const now = new Date().toISOString();
  await ref.set({ ...record, created_at: doc.data()?.created_at || now, updated_at: now });
  invalidateCustomPresets(uid);
  return toPresetShape(slug, { ...record, updated_at: now });
}
