"""Re-renders the homepage demo with the CURRENT engine, so the page never
describes a master visitors aren't hearing.

Writes:
  frontend/public/audio/demos/<name>-after.mp3   (delivery-checked MP3)
  frontend/src/content/demoMaster.js             (the report the page reads)

Usage (from backend/, with the engine's Python deps and ffmpeg installed):
  python scripts/render_homepage_demo.py                       # pop demo
  python scripts/render_homepage_demo.py --before ../frontend/public/audio/demos/rock-before.mp3 --genre rock

The source must be a mix you have the rights to publish.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from datetime import date
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
REPO = BACKEND.parent
sys.path.insert(0, str(BACKEND))

from adaptive_mastering import master_track  # noqa: E402
from app.services.mastering_service import deliver_and_verify  # noqa: E402


PLAN_KEYS = ("eq_decisions", "dynamic_eq_decisions", "compression", "rejected_decisions", "stereo", "loudness")
EVALUATION_KEYS = ("passed", "flags", "regions", "dynamics", "limiter", "true_peak_db", "problem_outcomes", "stereo", "loudness")


def git_commit() -> str:
    try:
        return subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=REPO, capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        return "unknown"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--before", default=str(REPO / "frontend/public/audio/demos/pop-before.mp3"))
    parser.add_argument("--genre", default="pop")
    parser.add_argument("--style", default="modern")
    args = parser.parse_args()

    before = Path(args.before).resolve()
    after_mp3 = before.with_name(before.name.replace("-before", "-after"))
    if after_mp3 == before:
        raise SystemExit("--before must be named <name>-before.<ext>")

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        source_wav = tmp / "source.wav"
        subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", str(before), "-ac", "2", "-ar", "44100", "-c:a", "pcm_s16le", str(source_wav)], check=True)
        master_wav = tmp / "master.wav"
        result = master_track(
            input_path=str(source_wav),
            output_path=str(master_wav),
            genre=args.genre,
            tags=[],
            tweaks={},
            style=args.style,
            enable_stem_separation=False,
            tier="standard",
        )
        delivery = deliver_and_verify(master_wav, after_mp3, "mp3")

    diag = result["processing_applied"].get("mastering_diagnostics") or result.get("mastering_diagnostics") or {}
    keep_analysis = ("integrated_lufs", "true_peak_db", "loudness_range_lu")
    demo = {
        "track": before.name,
        "genre": args.genre,
        "rendered": {"date": date.today().isoformat(), "engine_commit": git_commit(), "style": args.style, "tier": "standard"},
        "before_lufs": round(result["analysis_before"]["integrated_lufs"], 2),
        "after_lufs": round(result["analysis_after"]["integrated_lufs"], 2),
        "analysis_before": {k: result["analysis_before"].get(k) for k in keep_analysis},
        "analysis_after": {k: result["analysis_after"].get(k) for k in keep_analysis},
        "quality_control": {k: result["quality_control"].get(k) for k in ("passed", "checks", "warn_count", "fail_count")},
        "processing_applied": {
            "limiter": result["processing_applied"].get("limiter"),
            "delivery_check": delivery,
            # Only what frontend/src/lib/masteringDecisions.js reads — this
            # file ships in the homepage bundle.
            "mastering_diagnostics": {
                "engine": diag.get("engine"),
                "source_profile": diag.get("source_profile"),
                "detected_problems": diag.get("detected_problems"),
                "backoff_applied": diag.get("backoff_applied"),
                "mastering_plan": {k: (diag.get("mastering_plan") or {}).get(k) for k in PLAN_KEYS},
                "evaluation": {k: (diag.get("evaluation") or {}).get(k) for k in EVALUATION_KEYS},
            },
        },
    }

    header = (
        "// GENERATED by backend/scripts/render_homepage_demo.py — real output of the\n"
        "// current engine on the demo source, re-rendered together with the -after MP3.\n"
        "// Don't hand-edit: re-run the script whenever the engine changes, or the page\n"
        "// describes a master visitors aren't hearing. Numbers are from the\n"
        "// full-resolution master; the MP3 is its delivery-checked encode.\n"
    )
    out = REPO / "frontend/src/content/demoMaster.js"
    out.write_text(header + "export const DEMO_MASTER = " + json.dumps(demo, indent=1, default=float) + ";\n")
    ev = diag.get("evaluation") or {}
    print(f"{before.name}: {demo['before_lufs']} -> {demo['after_lufs']} LUFS")
    print(f"limiter: {ev.get('limiter')}")
    print(f"QC passed={demo['quality_control']['passed']} warnings={demo['quality_control']['warn_count']}")
    print(f"delivery: {delivery}")
    print(f"wrote {out.relative_to(REPO)} and {after_mp3.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
