// GENERATED by backend/scripts/render_homepage_demo.py — real output of the
// current engine on the demo source, re-rendered together with the -after MP3.
// Don't hand-edit: re-run the script whenever the engine changes, or the page
// describes a master visitors aren't hearing. Numbers are from the
// full-resolution master; the MP3 is its delivery-checked encode.
export const DEMO_MASTER = {
 "track": "pop-before.mp3",
 "genre": "pop",
 "rendered": {
  "date": "2026-09-28",
  "engine_commit": "de1a473",
  "style": "modern",
  "tier": "standard",
  "delivery": "auto"
 },
 "before_lufs": -15.89,
 "after_lufs": -11.26,
 "analysis_before": {
  "integrated_lufs": -15.888,
  "true_peak_db": -2.91,
  "loudness_range_lu": 2.206
 },
 "analysis_after": {
  "integrated_lufs": -11.255,
  "true_peak_db": -2.017,
  "loudness_range_lu": 1.82
 },
 "quality_control": {
  "passed": true,
  "checks": [
   {
    "id": "limiter_gain_reduction",
    "status": "warn",
    "message": "Limiter gain reduction of 5.4dB is moderate \u2014 worth listening for pumping.",
    "value": 5.378
   },
   {
    "id": "rendering_integrity",
    "status": "pass",
    "message": "Rendered audio contains only finite samples.",
    "value": null
   },
   {
    "id": "clipping",
    "status": "pass",
    "message": "No full-scale clipping in the final master.",
    "value": null
   },
   {
    "id": "true_peak",
    "status": "pass",
    "message": "True peak -2.02dBTP is within the -2.0dBTP ceiling.",
    "value": -2.017
   },
   {
    "id": "plr",
    "status": "pass",
    "message": "Peak-to-loudness ratio of 9.2dB is healthy.",
    "value": 9.237
   },
   {
    "id": "dynamics_preservation",
    "status": "pass",
    "message": "Dynamic range change (-4.5dB) is within normal mastering bounds.",
    "value": 4.453000000000001
   },
   {
    "id": "saturation_amount",
    "status": "pass",
    "message": "Saturation amount (0.000) is conservative.",
    "value": 0.0
   },
   {
    "id": "phase_correlation",
    "status": "pass",
    "message": "Phase correlation 0.64 is mono-safe.",
    "value": 0.6393
   },
   {
    "id": "mono_compatibility",
    "status": "pass",
    "message": "Master is mono-compatible.",
    "value": null
   },
   {
    "id": "output_silence",
    "status": "pass",
    "message": "Rendered master has audible signal.",
    "value": -14.435
   },
   {
    "id": "channel_balance",
    "status": "pass",
    "message": "L/R channels balanced within 0.2dB.",
    "value": 0.1763324873042773
   },
   {
    "id": "loudness_sanity",
    "status": "pass",
    "message": "Final integrated loudness (-11.3 LUFS) is plausible.",
    "value": -11.255
   },
   {
    "id": "dc_offset",
    "status": "pass",
    "message": "No meaningful DC offset in the final master.",
    "value": -72.52184778309523
   }
  ],
  "warn_count": 1,
  "fail_count": 0
 },
 "processing_applied": {
  "limiter": {
   "limiter_gain_reduction_db": 5.378,
   "pre_clipper_peak_db": 2.711,
   "pre_limiter_peak_db": 2.711,
   "post_limiter_peak_db": -2.673,
   "combined_peak_reduction_db": 4.728,
   "clipper_applied": false,
   "clipper_gain_reduction_db": 0.0,
   "release_ms": 129.3,
   "loudness_recovery_db": 0.835,
   "loudness_recovery_iterations": 1,
   "gr_at_p995_peaks_db": 3.919,
   "budget_db": 4.619
  },
  "delivery_check": {
   "format": "mp3",
   "checked": "decoded MP3",
   "ceiling_dbtp": -1.5,
   "gain_trim_db": 0.0,
   "encodes": 1,
   "passed": true,
   "finite": true,
   "clipped_samples": 0,
   "sample_peak_dbfs": -2.33,
   "true_peak_dbtp": -2.04
  },
  "mastering_diagnostics": {
   "engine": "adaptive_plan_v2",
   "source_profile": {
    "sample_rate": 44100,
    "duration_s": 33.672,
    "integrated_lufs": -15.888,
    "true_peak_db": -2.91,
    "sample_peak_db": -3.039,
    "rms_db": -19.237,
    "crest_db": 16.198,
    "short_term_crest_db": 12.523,
    "plr_db": 12.978,
    "lra_lu": 2.206,
    "peak_p995_db": -4.468,
    "spectral_bands": {
     "20_30hz": -19.272,
     "30_40hz": 2.562,
     "40_55hz": 7.819,
     "55_70hz": 2.631,
     "70_90hz": -1.62,
     "90_120hz": 0.743,
     "120_160hz": 1.617,
     "160_220hz": -0.272,
     "220_300hz": -1.819,
     "300_400hz": -1.801,
     "400_550hz": 0.203,
     "550_750hz": 0.565,
     "750_1000hz": 2.772,
     "1000_1400hz": 0.214,
     "1400_2000hz": 0.506,
     "2000_2800hz": -2.458,
     "2800_4000hz": -1.447,
     "4000_5500hz": -2.883,
     "5500_7500hz": -6.932,
     "7500_10000hz": -6.518,
     "10000_14000hz": -7.352,
     "14000_18000hz": -11.379,
     "18000_20000hz": -18.107
    },
    "band_levels_db": {
     "20_30hz": -48.897,
     "30_40hz": -28.698,
     "40_55hz": -23.088,
     "55_70hz": -29.543,
     "70_90hz": -34.772,
     "90_120hz": -30.518,
     "120_160hz": -30.232,
     "160_220hz": -31.439,
     "220_300hz": -33.011,
     "300_400hz": -33.288,
     "400_550hz": -30.935,
     "550_750hz": -30.723,
     "750_1000hz": -28.857,
     "1000_1400hz": -30.653,
     "1400_2000hz": -30.169,
     "2000_2800hz": -33.355,
     "2800_4000hz": -32.102,
     "4000_5500hz": -34.04,
     "5500_7500hz": -38.187,
     "7500_10000hz": -38.11,
     "10000_14000hz": -38.259,
     "14000_18000hz": -43.553,
     "18000_20000hz": -54.051
    },
    "band_layout": [
     {
      "name": "20_30hz",
      "lo_hz": 20.0,
      "hi_hz": 30.0,
      "center_hz": 24.5,
      "fft_bins": 2
     },
     {
      "name": "30_40hz",
      "lo_hz": 30.0,
      "hi_hz": 40.0,
      "center_hz": 34.6,
      "fft_bins": 2
     },
     {
      "name": "40_55hz",
      "lo_hz": 40.0,
      "hi_hz": 55.0,
      "center_hz": 46.9,
      "fft_bins": 3
     },
     {
      "name": "55_70hz",
      "lo_hz": 55.0,
      "hi_hz": 70.0,
      "center_hz": 62.0,
      "fft_bins": 3
     },
     {
      "name": "70_90hz",
      "lo_hz": 70.0,
      "hi_hz": 90.0,
      "center_hz": 79.4,
      "fft_bins": 3
     },
     {
      "name": "90_120hz",
      "lo_hz": 90.0,
      "hi_hz": 120.0,
      "center_hz": 103.9,
      "fft_bins": 6
     },
     {
      "name": "120_160hz",
      "lo_hz": 120.0,
      "hi_hz": 160.0,
      "center_hz": 138.6,
      "fft_bins": 7
     },
     {
      "name": "160_220hz",
      "lo_hz": 160.0,
      "hi_hz": 220.0,
      "center_hz": 187.6,
      "fft_bins": 11
     },
     {
      "name": "220_300hz",
      "lo_hz": 220.0,
      "hi_hz": 300.0,
      "center_hz": 256.9,
      "fft_bins": 15
     },
     {
      "name": "300_400hz",
      "lo_hz": 300.0,
      "hi_hz": 400.0,
      "center_hz": 346.4,
      "fft_bins": 19
     },
     {
      "name": "400_550hz",
      "lo_hz": 400.0,
      "hi_hz": 550.0,
      "center_hz": 469.0,
      "fft_bins": 28
     },
     {
      "name": "550_750hz",
      "lo_hz": 550.0,
      "hi_hz": 750.0,
      "center_hz": 642.3,
      "fft_bins": 37
     },
     {
      "name": "750_1000hz",
      "lo_hz": 750.0,
      "hi_hz": 1000.0,
      "center_hz": 866.0,
      "fft_bins": 46
     },
     {
      "name": "1000_1400hz",
      "lo_hz": 1000.0,
      "hi_hz": 1400.0,
      "center_hz": 1183.2,
      "fft_bins": 75
     },
     {
      "name": "1400_2000hz",
      "lo_hz": 1400.0,
      "hi_hz": 2000.0,
      "center_hz": 1673.3,
      "fft_bins": 111
     },
     {
      "name": "2000_2800hz",
      "lo_hz": 2000.0,
      "hi_hz": 2800.0,
      "center_hz": 2366.4,
      "fft_bins": 149
     },
     {
      "name": "2800_4000hz",
      "lo_hz": 2800.0,
      "hi_hz": 4000.0,
      "center_hz": 3346.6,
      "fft_bins": 223
     },
     {
      "name": "4000_5500hz",
      "lo_hz": 4000.0,
      "hi_hz": 5500.0,
      "center_hz": 4690.4,
      "fft_bins": 278
     },
     {
      "name": "5500_7500hz",
      "lo_hz": 5500.0,
      "hi_hz": 7500.0,
      "center_hz": 6422.6,
      "fft_bins": 372
     },
     {
      "name": "7500_10000hz",
      "lo_hz": 7500.0,
      "hi_hz": 10000.0,
      "center_hz": 8660.3,
      "fft_bins": 464
     },
     {
      "name": "10000_14000hz",
      "lo_hz": 10000.0,
      "hi_hz": 14000.0,
      "center_hz": 11832.2,
      "fft_bins": 743
     },
     {
      "name": "14000_18000hz",
      "lo_hz": 14000.0,
      "hi_hz": 18000.0,
      "center_hz": 15874.5,
      "fft_bins": 743
     },
     {
      "name": "18000_20000hz",
      "lo_hz": 18000.0,
      "hi_hz": 20000.0,
      "center_hz": 18973.7,
      "fft_bins": 372
     }
    ],
    "segment_percentiles": {
     "20_30hz": {
      "5": -25.053,
      "10": -24.674,
      "25": -23.151,
      "50": -19.185,
      "75": -17.265,
      "90": -16.625,
      "95": -16.369
     },
     "30_40hz": {
      "5": -8.787,
      "10": -8.387,
      "25": -6.312,
      "50": 3.08,
      "75": 4.459,
      "90": 4.762,
      "95": 5.25
     },
     "40_55hz": {
      "5": 4.181,
      "10": 4.693,
      "25": 6.349,
      "50": 7.693,
      "75": 9.19,
      "90": 9.914,
      "95": 10.147
     },
     "55_70hz": {
      "5": -0.658,
      "10": 0.305,
      "25": 0.735,
      "50": 1.87,
      "75": 5.509,
      "90": 6.704,
      "95": 7.041
     },
     "70_90hz": {
      "5": -4.253,
      "10": -3.668,
      "25": -2.496,
      "50": -1.287,
      "75": -0.37,
      "90": 0.225,
      "95": 0.244
     },
     "90_120hz": {
      "5": -2.129,
      "10": -1.46,
      "25": -0.818,
      "50": 1.377,
      "75": 2.199,
      "90": 3.156,
      "95": 3.785
     },
     "120_160hz": {
      "5": -0.835,
      "10": -0.462,
      "25": 0.546,
      "50": 2.056,
      "75": 3.573,
      "90": 4.082,
      "95": 4.23
     },
     "160_220hz": {
      "5": -2.625,
      "10": -1.778,
      "25": -1.077,
      "50": -0.654,
      "75": 1.066,
      "90": 2.295,
      "95": 2.314
     },
     "220_300hz": {
      "5": -4.216,
      "10": -4.099,
      "25": -3.027,
      "50": -1.942,
      "75": -0.494,
      "90": 0.698,
      "95": 1.026
     },
     "300_400hz": {
      "5": -4.834,
      "10": -4.438,
      "25": -2.408,
      "50": -1.444,
      "75": -0.528,
      "90": 0.76,
      "95": 1.146
     },
     "400_550hz": {
      "5": -4.173,
      "10": -2.934,
      "25": -2.392,
      "50": -0.369,
      "75": 1.064,
      "90": 2.864,
      "95": 3.906
     },
     "550_750hz": {
      "5": -3.868,
      "10": -3.207,
      "25": -1.214,
      "50": 0.173,
      "75": 2.329,
      "90": 3.419,
      "95": 4.138
     },
     "750_1000hz": {
      "5": -1.288,
      "10": -0.753,
      "25": 0.407,
      "50": 2.33,
      "75": 3.38,
      "90": 6.187,
      "95": 7.076
     },
     "1000_1400hz": {
      "5": -1.375,
      "10": -1.238,
      "25": -0.697,
      "50": 0.019,
      "75": 1.308,
      "90": 3.89,
      "95": 4.334
     },
     "1400_2000hz": {
      "5": -0.936,
      "10": -0.314,
      "25": -0.039,
      "50": 0.609,
      "75": 1.785,
      "90": 2.533,
      "95": 2.798
     },
     "2000_2800hz": {
      "5": -3.884,
      "10": -3.689,
      "25": -3.16,
      "50": -2.407,
      "75": -1.179,
      "90": 0.593,
      "95": 0.804
     },
     "2800_4000hz": {
      "5": -3.014,
      "10": -2.341,
      "25": -1.683,
      "50": -1.175,
      "75": -0.266,
      "90": 0.174,
      "95": 0.356
     },
     "4000_5500hz": {
      "5": -4.546,
      "10": -3.89,
      "25": -3.169,
      "50": -2.514,
      "75": -1.988,
      "90": -0.862,
      "95": -0.74
     },
     "5500_7500hz": {
      "5": -11.023,
      "10": -10.462,
      "25": -8.785,
      "50": -6.469,
      "75": -5.702,
      "90": -5.052,
      "95": -4.745
     },
     "7500_10000hz": {
      "5": -9.923,
      "10": -8.933,
      "25": -7.591,
      "50": -6.155,
      "75": -5.029,
      "90": -4.712,
      "95": -4.649
     },
     "10000_14000hz": {
      "5": -9.722,
      "10": -9.003,
      "25": -8.438,
      "50": -7.578,
      "75": -6.689,
      "90": -4.544,
      "95": -4.328
     },
     "14000_18000hz": {
      "5": -14.528,
      "10": -14.328,
      "25": -13.222,
      "50": -12.691,
      "75": -10.712,
      "90": -8.582,
      "95": -8.333
     },
     "18000_20000hz": {
      "5": -29.567,
      "10": -28.457,
      "25": -25.796,
      "50": -22.394,
      "75": -20.472,
      "90": -18.462,
      "95": -10.625
     }
    },
    "segment_count": 22,
    "spectral_tilt": -1.123,
    "spectral_centroid": 862.2,
    "spectral_rolloff_85": 1555.8,
    "codec_cutoff_hz": null,
    "resonances": [],
    "transient_strength": 0.2688,
    "transient_density": 0.3101,
    "transient_contrast": 0.1167,
    "low_end_impact": 0.3504,
    "drum_punch_estimate": 0.3055,
    "stereo_width": 0.4798,
    "stereo_correlation": 0.6259,
    "width_per_band": {
     "20_30hz": 0.1252,
     "30_40hz": 0.0243,
     "40_55hz": 0.0157,
     "55_70hz": 0.0505,
     "70_90hz": 0.1361,
     "90_120hz": 0.1368,
     "120_160hz": 0.3999,
     "160_220hz": 0.5653,
     "220_300hz": 0.5442,
     "300_400hz": 0.6558,
     "400_550hz": 0.6226,
     "550_750hz": 0.7026,
     "750_1000hz": 0.6751,
     "1000_1400hz": 0.6452,
     "1400_2000hz": 0.7817,
     "2000_2800hz": 0.8778,
     "2800_4000hz": 0.7472,
     "4000_5500hz": 0.6936,
     "5500_7500hz": 0.6402,
     "7500_10000hz": 0.5884,
     "10000_14000hz": 0.6126,
     "14000_18000hz": 0.5399,
     "18000_20000hz": 0.2885
    },
    "stereo_regions": {
     "low_20_120hz": {
      "width": 0.0569,
      "correlation": 0.9936
     },
     "low_mid_120_500hz": {
      "width": 0.5506,
      "correlation": 0.5347
     },
     "mid_500_2000hz": {
      "width": 0.7021,
      "correlation": 0.3397
     },
     "high_mid_2000_6000hz": {
      "width": 0.7773,
      "correlation": 0.2467
     },
     "high_6000hz_up": {
      "width": 0.606,
      "correlation": 0.4629
     }
    },
    "low_end_stereo_width": 0.0569,
    "low_end_correlation": 0.9936,
    "mid_stereo_width": 0.7021,
    "high_stereo_width": 0.606,
    "near_mono": false,
    "tempo_bpm": 126.05,
    "bpm_confidence": 0.918,
    "clipping": {
     "clipped_sample_fraction": 0.0,
     "longest_clipped_run": 0,
     "clipped_runs": 0,
     "detected": false
    },
    "sibilance": {
     "score": 0.0,
     "center_hz": 5408.3,
     "jump_db": 0.92,
     "event_fraction": 0.0357,
     "centred_ratio": 0.547
    },
    "mud_score": 0.0,
    "boom_score": 0.0,
    "thinness_score": 0.769,
    "harshness_score": 0.023,
    "sibilance_score": 0.0,
    "brightness_score": 0.419,
    "dullness_score": 0.0,
    "transient_health": 0.526,
    "dynamic_health_score": 0.854,
    "already_limited_score": 0.0,
    "score_basis": {
     "reference": "neutral curve (genre independent)",
     "region_deviation_db": {
      "boom_90_220": -6.06,
      "mud_220_550": -3.92,
      "body_55_300": -6.61,
      "harsh_2k_7k5": 2.14,
      "bright_7k5_14k": 4.44,
      "air_14k_up": 4.59
     }
    }
   },
   "detected_problems": {
    "insufficient_sub": {
     "kind": "insufficient_sub",
     "category": "tonal",
     "severity": 1.0,
     "confidence": 0.667,
     "evidence": {
      "outside_window_db": 17.849,
      "persistence": 1.0,
      "reliability": 0.667,
      "lo_hz": 20.0,
      "hi_hz": 30.0,
      "per_band_deviation_db": {
       "20_30hz": -22.85
      }
     },
     "direction": "deficit",
     "center_hz": 24.5,
     "bandwidth_oct": 0.585,
     "q": null,
     "measured_deviation_db": -22.849,
     "bands": [
      "20_30hz"
     ],
     "frequency_class": "low",
     "actionable": true
    },
    "thin_body": {
     "kind": "thin_body",
     "category": "tonal",
     "severity": 0.464,
     "confidence": 0.779,
     "evidence": {
      "outside_window_db": 2.786,
      "persistence": 0.967,
      "reliability": 1.0,
      "lo_hz": 55.0,
      "hi_hz": 400.0,
      "per_band_deviation_db": {
       "55_70hz": -5.02,
       "70_90hz": -9.43,
       "90_120hz": -6.72,
       "120_160hz": -4.98,
       "160_220hz": -5.63,
       "220_300hz": -5.81,
       "300_400hz": -4.63
      }
     },
     "direction": "deficit",
     "center_hz": 134.342,
     "bandwidth_oct": 2.862,
     "q": null,
     "measured_deviation_db": -5.983,
     "bands": [
      "55_70hz",
      "70_90hz",
      "90_120hz",
      "120_160hz",
      "160_220hz",
      "220_300hz",
      "300_400hz"
     ],
     "frequency_class": "low",
     "actionable": true
    },
    "harsh_upper_mids": {
     "kind": "harsh_upper_mids",
     "category": "tonal",
     "severity": 0.079,
     "confidence": 0.234,
     "evidence": {
      "outside_window_db": 0.476,
      "persistence": 0.97,
      "reliability": 1.0,
      "lo_hz": 2800.0,
      "hi_hz": 5500.0,
      "per_band_deviation_db": {
       "2800_4000hz": 3.34,
       "4000_5500hz": 3.63
      }
     },
     "direction": "excess",
     "center_hz": 4130.079,
     "bandwidth_oct": 0.974,
     "q": null,
     "measured_deviation_db": 3.476,
     "bands": [
      "2800_4000hz",
      "4000_5500hz"
     ],
     "frequency_class": "high",
     "actionable": true
    },
    "excessive_brightness": {
     "kind": "excessive_brightness",
     "category": "tonal",
     "severity": 0.254,
     "confidence": 0.562,
     "evidence": {
      "outside_window_db": 1.526,
      "persistence": 0.948,
      "reliability": 1.0,
      "lo_hz": 7500.0,
      "hi_hz": 14000.0,
      "per_band_deviation_db": {
       "7500_10000hz": 4.05,
       "10000_14000hz": 6.36
      }
     },
     "direction": "excess",
     "center_hz": 11233.459,
     "bandwidth_oct": 0.9,
     "q": null,
     "measured_deviation_db": 5.295,
     "bands": [
      "7500_10000hz",
      "10000_14000hz"
     ],
     "frequency_class": "high",
     "actionable": true
    },
    "below_loudness_range": {
     "kind": "below_loudness_range",
     "category": "loudness",
     "severity": 0.211,
     "confidence": 0.95,
     "evidence": {
      "integrated_lufs": -15.888,
      "acceptable_min_lufs": -13.78
     },
     "direction": null,
     "center_hz": null,
     "bandwidth_oct": null,
     "q": null,
     "measured_deviation_db": null,
     "bands": [],
     "frequency_class": null,
     "actionable": true
    }
   },
   "backoff_applied": true,
   "mastering_plan": {
    "eq_decisions": [
     {
      "filter_type": "bell",
      "frequency_hz": 35.0,
      "gain_db": 1.0,
      "q": 2.5,
      "confidence": 0.667,
      "reason": "measured_insufficient_sub",
      "source": "automatic",
      "problem": "insufficient_sub",
      "notes": []
     },
     {
      "filter_type": "bell",
      "frequency_hz": 134.342,
      "gain_db": 0.869,
      "q": 0.5,
      "confidence": 0.779,
      "reason": "measured_thin_body",
      "source": "automatic",
      "problem": "thin_body",
      "notes": []
     },
     {
      "filter_type": "bell",
      "frequency_hz": 11233.459,
      "gain_db": -0.715,
      "q": 1.757,
      "confidence": 0.562,
      "reason": "measured_excessive_brightness",
      "source": "automatic",
      "problem": "excessive_brightness",
      "notes": []
     }
    ],
    "dynamic_eq_decisions": [
     {
      "frequency_hz": 1090.92,
      "q": 1.0,
      "max_reduction_db": 1.504,
      "threshold_percentile": 80.0,
      "release_ms": 120.0,
      "confidence": 0.658,
      "reason": "intermittent excess around 1091 Hz (hot in 28% of segments)",
      "problem": null
     }
    ],
    "compression": {
     "need": {
      "micro_need": 0.0,
      "macro_need": 0.0,
      "inputs": {
       "limiter_only_achievable_lufs": -8.8,
       "acceptable_min_lufs": -13.78,
       "loudness_shortfall_lu": -4.98,
       "crest_db": 16.198,
       "short_term_crest_db": 12.523,
       "lra_lu": 2.206,
       "plr_db": 12.978,
       "transient_health": 0.526,
       "transient_density": 0.3101
      }
     },
     "multiband": {
      "enabled": false
     },
     "glue": {
      "enabled": false
     },
     "enabled": false,
     "attack_basis": "transient health 0.53 x priority 0.75 -> base attack 36.8 ms"
    },
    "rejected_decisions": [
     {
      "stage": "eq",
      "problem": "harsh_upper_mids",
      "reason": "confidence 0.23 below cut gate 0.42"
     },
     {
      "stage": "compression",
      "problem": "micro_dynamics",
      "reason": "need 0.00 below 0.20 (limiter alone reaches -8.8 LUFS vs acceptable min -13.8; transient health 0.53; already-limited 0.00)"
     },
     {
      "stage": "glue_compression",
      "problem": "macro_dynamics",
      "reason": "need 0.00 below 0.25 (LRA 2.2 LU)"
     },
     {
      "stage": "saturation",
      "problem": null,
      "reason": "amount 0.017 below 0.03 (allowance 0.100, factors {'hf_suitability': 0.27, 'transient_protection': 0.724, 'not_already_limited': 1.0, 'not_clipped': 1.0, 'identity': 0.89})"
     },
     {
      "stage": "clipper",
      "problem": null,
      "reason": "limiter budget sufficient"
     }
    ],
    "stereo": {
     "lf_mono": {
      "enabled": false
     },
     "side_gain_db": 0.0,
     "side_high_shelf_db": 0.0,
     "side_shelf_hz": 1500.0,
     "reasons": [
      "stereo image within limits: no width processing"
     ],
     "enabled": false
    },
    "loudness": {
     "source_lufs": -15.89,
     "preferred_lufs": -10.0,
     "acceptable_min_lufs": -13.78,
     "acceptable_max_lufs": -9.0,
     "desired_lufs": -10.0,
     "achievable_lufs_by_budget": -8.8,
     "target_lufs": -11.1,
     "constrained_by_limiter_budget": false,
     "notes": []
    }
   },
   "evaluation": {
    "passed": true,
    "flags": [],
    "regions": {
     "sub_30_55": {
      "actual_db": 0.42,
      "planned_db": 0.741,
      "collateral_db": -0.321
     },
     "low_end_40_120": {
      "actual_db": 0.548,
      "planned_db": 0.579,
      "collateral_db": -0.031
     },
     "low_mid_120_500": {
      "actual_db": 0.566,
      "planned_db": 0.444,
      "collateral_db": 0.122
     },
     "mid_500_4k": {
      "actual_db": -0.121,
      "planned_db": -0.087,
      "collateral_db": -0.034
     },
     "hf_4k_14k": {
      "actual_db": -0.281,
      "planned_db": -0.362,
      "collateral_db": 0.081
     },
     "air_14k_up": {
      "actual_db": -0.143,
      "planned_db": -0.19,
      "collateral_db": 0.048
     }
    },
    "dynamics": {
     "crest_before_db": 16.198,
     "crest_after_db": 11.745,
     "crest_change_db": -4.453,
     "short_term_crest_change_db": -1.136,
     "short_term_crest_before_db": 12.523,
     "short_term_crest_after_db": 11.387,
     "lra_before_lu": 2.206,
     "lra_after_lu": 1.82,
     "plr_before_db": 12.978,
     "plr_after_db": 9.237
    },
    "limiter": {
     "gr_at_p995_peaks_db": 3.919,
     "budget_db": 4.619,
     "max_gr_db": 5.378
    },
    "true_peak_db": -2.017,
    "problem_outcomes": {
     "insufficient_sub": {
      "outside_window_before_db": 17.849,
      "outside_window_after_db": 17.646,
      "improved": true,
      "unchanged": false
     },
     "thin_body": {
      "outside_window_before_db": 2.816,
      "outside_window_after_db": 2.189,
      "improved": true,
      "unchanged": false
     },
     "harsh_upper_mids": {
      "outside_window_before_db": 0.484,
      "outside_window_after_db": 0.416,
      "improved": false,
      "unchanged": true
     },
     "excessive_brightness": {
      "outside_window_before_db": 1.455,
      "outside_window_after_db": 1.017,
      "improved": true,
      "unchanged": false
     }
    },
    "stereo": {
     "width_before": 0.4798,
     "width_after": 0.4692,
     "correlation_before": 0.6259,
     "correlation_after": 0.6393,
     "low_end_width_before": 0.0569,
     "low_end_width_after": 0.0592
    },
    "loudness": {
     "integrated_lufs": -11.255,
     "target_lufs": -11.1,
     "acceptable_min_lufs": -13.78,
     "acceptable_max_lufs": -9.0,
     "in_acceptable_range": true
    }
   }
  }
 }
};
